/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aula13;

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class TelaAula13 extends javax.swing.JFrame {

    /**
     * Creates new form TelaAula13
     */
    public TelaAula13() {
        initComponents();
        rbtnJava.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnConferir = new javax.swing.JButton();
        rbtnJava = new javax.swing.JRadioButton();
        rbtnJavaScript = new javax.swing.JRadioButton();
        rbtnPyton = new javax.swing.JRadioButton();
        rbtnCSharp = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Qual é  a melhor  linguagem programção do mundo?");
        lblTitulo.setToolTipText("");

        btnConferir.setText("Conferir!");
        btnConferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConferirActionPerformed(evt);
            }
        });

        rbtnJava.setText("Java");
        rbtnJava.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtnJavaStateChanged(evt);
            }
        });

        rbtnJavaScript.setText("JavaScript");

        rbtnPyton.setText("Pyton");
        rbtnPyton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPytonActionPerformed(evt);
            }
        });

        rbtnCSharp.setText("CSharp");
        rbtnCSharp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCSharpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBaseLayout = new javax.swing.GroupLayout(pnlBase);
        pnlBase.setLayout(pnlBaseLayout);
        pnlBaseLayout.setHorizontalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnJava)
                            .addComponent(rbtnPyton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnJavaScript)
                            .addComponent(rbtnCSharp))
                        .addGap(65, 65, 65))
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                            .addComponent(btnConferir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        pnlBaseLayout.setVerticalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(47, 47, 47)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnJava)
                    .addComponent(rbtnJavaScript))
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(rbtnPyton))
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(rbtnCSharp)))
                .addGap(34, 34, 34)
                .addComponent(btnConferir)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConferirActionPerformed
        if (rbtnJava.isSelected()) {
            String mensagem = "Voce esta redondamente certo! Bom garoto!";
            JOptionPane.showMessageDialog(null,mensagem);
        }
        
        if (rbtnJavaScript.isSelected()) {
            String mensagem = "JavaScript é ruim!";
            JOptionPane.showMessageDialog(null,mensagem);
        }
        
        if (rbtnPyton.isSelected()) {
            String mensagem = "JavaScript é ruim!";
            JOptionPane.showMessageDialog(null,mensagem);
        }
    }//GEN-LAST:event_btnConferirActionPerformed

    private void rbtnJavaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtnJavaStateChanged
        if (rbtnJava.isSelected())
            rbtnJavaScript.setSelected(false);
    }//GEN-LAST:event_rbtnJavaStateChanged

    private void rbtnPytonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPytonActionPerformed
        if (rbtnPyton.isSelected()) {
            String mensagem = "Voce esta redodamente certo!";
            JOptionPane.showConfirmDialog(null, mensagem);
            
        }

    }//GEN-LAST:event_rbtnPytonActionPerformed

    private void rbtnCSharpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCSharpActionPerformed
        if (rbtnCSharp.isSelected()) {
            String mensagem = "Nops!";
            JOptionPane.showConfirmDialog(null, mensagem);
    }//GEN-LAST:event_rbtnCSharpActionPerformed
        if (!rbtnCSharp.isSelected()) {
            rbtnJava.setSelected(true);
        }
        /**
         * @param args the command line arguments
         
         *  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAula13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAula13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAula13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAula13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAula13().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConferir;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBase;
    private javax.swing.JRadioButton rbtnCSharp;
    private javax.swing.JRadioButton rbtnJava;
    private javax.swing.JRadioButton rbtnJavaScript;
    private javax.swing.JRadioButton rbtnPyton;
    // End of variables declaration//GEN-END:variables

    private void setSelected(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
